### ISSUE TITLE
dedupe parsing between eth2-package and eth-network-package

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/eth2-package#161]
perhaps eth2 can just call down to eth-network?

**Comment by barnabasbusa** [comment]
@leeederek  this is a completely different issue.

What @h4ck3rk3y made this issue for is to remove the redundant input parser from eth2-packages and use the upstream one (eth-network-package) instead.

**Comment by leeederek** [comment]
Thanks @barnabasbusa, you're right. Reopening this issue.
