### ISSUE TITLE
add ability to pass in custom image for mev-builder and mev-boost

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/eth2-package#169]
currently both are hardcoded one in parse_input.star and the other in mev_boost_launcher.star

bchain99 asked for this.

**Comment by h4ck3rk3y** [comment]
@bharath-123 is interested in this, can you plus one the issue? I can't assign you just yet!!

**Comment by bharath-123** [comment]
please do assign to me!
