### ISSUE TITLE
fix a bug with erigon assuming that a node already exists as opposed to being the bootnode itself

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/eth2-package#55]
https://github.com/kurtosis-tech/eth2-merge-kurtosis-module/blob/158e5101fb53875d1aa64fa7c0f0f3ba58fcbbc8/kurtosis-module/impl/participant_network/el/erigon/erigon_launcher.go#L140

Can this node be the boot node then? Or is it only geth that can be the 0th node?

**Comment by remoterami** [comment]
What's the status of this issue? It's marked as closed, but I can't get erigon to work as an el client (neither with 1 nor 2 participants). Still getting [Erigon needs at least one node to exist, which it treats as the bootnode](https://github.com/kurtosis-tech/ethereum-package/blob/main/src/el/erigon/erigon_launcher.star#L162)

**Comment by parithosh** [comment]
definitely needs the check removed, cc @h4ck3rk3y
