### ISSUE TITLE
Report eth2-package v0.70

### ISSUE THREAD

**Issue by avenbreaks** [kurtosis-tech/eth2-package#81]
cannot running on latest version 0.70.0

error msg: 
```
here was an error interpreting Starlark code 
Evaluation error: ExecRecipe: unexpected keyword argument "service_name"
	at [github.com/kurtosis-tech/eth2-package:33:88]: run
	at [github.com/kurtosis-tech/eth2-package/src/participant_network/participant_network.star:50:76]: launch_participant_network
	at [github.com/kurtosis-tech/eth2-package/src/participant_network/prelaunch_data_generator/cl_validator_keystores/cl_validator_keystore_generator.star:69:39]: generate_cl_validator_keystores
	at [0:0]: ExecRecipe

Error encountered running Starlark code.
```
Screenshot Running on v0.70.0 : 
![image](https://user-images.githubusercontent.com/93043826/227797764-2086b11f-2071-418c-b865-fbb2dfb24a5e.png)

Screenshot Running on v0.68.0 : 
![image](https://user-images.githubusercontent.com/93043826/227797799-117e4dcc-a58f-402f-b6e7-edb2c3135553.png)
![image](https://user-images.githubusercontent.com/93043826/227797657-1520b5a2-315e-463e-af1e-b96d9fce24e3.png)

And please update the package running on cloud vm : 
![image](https://user-images.githubusercontent.com/93043826/227797862-d36ca459-184d-48f1-9b12-1620b0fe007f.png)

**Comment by gbouv** [comment]
Hey @avenbreaks !
Good catch, we merged [this PR](https://github.com/kurtosis-tech/eth2-package/pull/80) earlier today to fix this issue. Can you retry with the latest version? This should hopefully unblock you.
Let me know if you hit any other blocker

**Comment by avenbreaks** [comment]
> 

i will try

**Comment by avenbreaks** [comment]
yea is return : 
```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by gbouv** [comment]
Hmm, this is definitely weird, I just tried it locally and it works as expected.
My first question is why are you on the master branch? Default branch is `main` for this repo. Are you on a custom branch or something?

Can we maybe start from a fresh clone?
1. Upgrade your kurtosis to latest, which is `0.71.0`
```
> kurtosis version
CLI Version:              0.71.0
Running Engine Version:   0.71.0
```

2. clone this as a fresh repo 
```
> git clone git@github.com:kurtosis-tech/eth2-package.git eth2-package-fresh-clone
Cloning into 'eth2-package-fresh-clone'...
remote: Enumerating objects: 2761, done.
remote: Counting objects: 100% (1194/1194), done.
remote: Compressing objects: 100% (462/462), done.
remote: Total 2761 (delta 642), reused 1063 (delta 591), pack-reused 1567
Receiving objects: 100% (2761/2761), 539.29 KiB | 1.38 MiB/s, done.
Resolving deltas: 100% (1533/1533), done.
```

3. Run it:
```
> cd eth2-package-fresh-clone
> kurtosis run main.star
INFO[2023-03-29T18:44:14+02:00] Creating a new enclave for Starlark to run inside...
INFO[2023-03-29T18:44:18+02:00] Enclave 'howling-crag' created successfully
INFO[2023-03-29T18:44:18+02:00] Executing Starlark package at '/Users/gbouvignies/git/eth2-package-fresh-clone' as the passed argument '.' looks like a directory
INFO[2023-03-29T18:44:18+02:00] Compressing package 'github.com/kurtosis-tech/eth2-package' at '.' for upload
INFO[2023-03-29T18:44:18+02:00] Uploading and executing package 'github.com/kurtosis-tech/eth2-package'
.....
```

Let me know how that goes. I'm trying to narrow down the issue here to better understand what's going on, as I can't repro it easily

**Comment by gbouv** [comment]
Closing as stale. Feel free to re-open if this is still an issue.
