### ISSUE TITLE
Replace `wait` instructions with adding `ServiceConfig.ready_conditions`

### ISSUE THREAD

**Issue by leoporoli** [kurtosis-tech/eth2-package#86]

**Comment by leoporoli** [comment]
There is only one `plan.wait` instruction in the eth2-package and can't be replaced by the ReadyConditions type because it is not executed during the start-up.

It was possible to do the replace in the `ethereum-network-package`

**Comment by h4ck3rk3y** [comment]
Closing this as its finished (eth-network-package)
